# Generated by Django 2.0.3 on 2018-05-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('website', models.URLField(default='')),
                ('phone', models.CharField(default='', max_length=12)),
                ('role', models.CharField(default='employee', max_length=10)),
                ('CV', models.FileField(upload_to='')),
                ('project', models.FileField(upload_to='')),
            ],
        ),
    ]
