# Generated by Django 2.0.3 on 2018-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
