# Generated by Django 2.0.3 on 2018-04-27 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20180426_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MsUser',
            new_name='Profile',
        ),
    ]
